### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by Ray-Eldath** [ayanamists/ayanamists.github.io#10]
你好，偶然在群里看到了你的博客，很想订阅一下，但是发现好像没有生成 RSS。

看了好几篇文章，感觉都非常棒。非常希望能[有 RSS 订阅](https://github.com/hexojs/hexo-generator-feed)。

**Comment by ayanamists** [comment]
谢谢夸奖，这个功能之后也许会添加，这个月沉迷原神😂

**Comment by ayanamists** [comment]
目前已经支持

[链接](https://ayayaya.org/zh-cn/index.xml)
